version: "3.5"

services:
  db:
    container_name: db
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: aula

volumes:
  db-data:
